#!/usr/bin/env bash
# configures nginx server to listen to port 80
sudo rm /etc/nginx/stite-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
