#!/usr/bin/env bash
# installs and configures nginx server to listen at port 80 only

sudo apt update;
sudo apt-get install -y nginx;
sudo ufw allow 'Nginx HTTP'

sudo echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	location /{
		try_riles \$uri \$uri/ =404;
	}

	location /{
	return 200 'Hello World!';
	}
}" > /etc/nginx/sites-available/default

service nginx restart
