#!/usr/bin/env bash
# installs and configures nginx server to listen at port 80 only
sudo apt purge nginx nginx-common nginx-core -y
sudo apt update;
sudo apt install -y nginx;
sudo ufw allow 'Nginx HTTP';
sudo chown -R "$USER":"$USER" /var/www/html;
sudo chown -R "$USER":"$USER" /etc/nginx;
sudo tee /var/www/html/index.html > /dev/null <<EOT
Hello World!
EOT

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
                   listen       80 default_server;
                   listen       [::]:80 default_server;

                   root         /var/www/html;
                   index        index.html index.htm;

                   #location /{
                   #           try_files \$uri \$uri/ =404;
                   #}

                   #location /{
                   #           return 200 'Hello World!';
                   #}
          }
EOT
# sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
