#!/usr/bin/env bash
# installs and configures nginx server to listen at port 80 only

sudo apt update;
sudo apt install -y nginx;
sudo ufw allow 'Nginx HTTP';
sudo chown -R $USER:$USER /var/www/html;
sudo echo "Hello World!" > /var/www/html/index.html;

sudo echo "server {
                   listen       80 default_server;
                   listen       [::]:80 default_server;

                   root         /etc/nginx/html;
                   index        index.html index.htm;

                   location /{
                              try_files \$uri \$uri/ =404;
                   }

                   location /{
                              return 200 'Hello World!';
                   }
          }" > /etc/nginx/sites-available/default;

sudo service nginx restart
