#!/usr/bin/env bash
# installs and configures nginx server to listen at port 80 only

echo "server {
                   listen       80 default_server;
                   listen       [::]:80 default_server;

                   root         /etc/nginx/html;
                   index        index.html index.htm;

                   location /{
                              try_files \$uri \$uri/ =404;
                   }

                   location /{
                              return 200 'Hello World!';
		   }
		   location /redirect_me {
			      root 
			      return 301 /etc/nginx/html/index.html
                   }
          }" > /etc/nginx/sites-available/default;

sudo service nginx restart
