#!/usr/bin/env bash
# installs and configures nginx server to listen at port 80 only
sudo apt purge nginx nginx-common nginx-core -y;
sudo apt update;
sudo apt install nginx -y;
sudo ufw allow 'Nginx HTTP';
sudo chown -R "$USER":"$USER" /var/www/html;
sudo chown -R "$USER":"$USER" /etc/nginx/;
sudo tee /var/www/html/index.html > /dev/null <<EOT
Hello World!
EOT

sudo tee /var/www/html/custom_404.html > /dev/null <<EOT
Ceci n'est pas une page
EOT

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
                   listen       80 default_server;
                   listen       [::]:80 default_server;
                   server_name  zayabell.tech 54.236.41.129;

                   root         /var/www/html;
                   index        index.html index.htm;

                   location /redirect_me {
                              return 301 http://zayabell.tech;
                   }

                   error_page   404 /custom_404.html;

                   location = /custom_404.html {
                        internal;
                   }
          }
EOT
# sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/;
sudo service nginx restart
