#!/usr/bin/env bash
# installs and configures haproxy to feed traffic to my web servers

# sudo apt-get remove haproxy -y
# sudo apt-get install --no-install-recommends software-properties-common -y
# sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend my_web_front
        bind *:80
        mode http
        default_backend my_web_back

backend my_web_back
        mode http
        balance roundrobin
        server 173544-web-01 3.84.158.163:80 check
        server 173544-web-02 100.26.169.53:80 check
EOT
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chmod +700 /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy start;
sudo systemctl enable haproxy;
sudo service haproxy restart;
