#!/usr/bin/env bash
# displays number 1-100 except multiples of 3 or/and 5

for i in {1..100}
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0  ]
	then
		echo "FizzBuzz"
	elif [ $((i%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
