#!/usr/bin/env bash
# Prints "Best School" for all iterations except 4 and 8 for which it 
#+ prints "bad luck" and "good luck" respectively

i=1
while [ $i -le 10 ]
do 
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
