#!/usr/bin/env bash
# displays No. 1-20 and additionally
#+ badluck from China, bad luck from Japan, bad luck from italy after 4, 9, 17 
#+ respectively

i=1
while [[ $i -le 20 ]]
do 
	case $i in
		4) 
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i=i+1))
done
