#!/usr/bin/env bash
# Displays a clock count; 0 - 12 hrs, 1 - 59 min

i=0
while [ $i -le 12 ]
do
	j=1
	echo "Hour: $i"
	while [ $j -le 59 ]
	do
		echo "$j"
		j=$((j = j + 1))
	done
	i=$((i = i + 1))
done
