#!/usr/bin/env bash
#use firewall to deny all incoming traffic except ssh, http, and https

sudo ufw default deny incoming;
sudo ufw allow ssh;
sudo ufw allow http;
sudo ufw allow https;
sudo ufw enable
