#!/usr/bin/env bash
# configures nginx as nginx user
apt-get update
apt-get install -y nginx

mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

cat <<EOF > /etc/nginx/nginx.conf
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
EOF
sudo service nginx restart
